import React from 'react';
import { Router, hashHistory } from 'react-router';
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import Dashboard from './pages/Dashboard';
import Newdash from './pages/Newdash';

import { UserList, EditPassword, UserProfile } from './pages/User';

import AreaList from './pages/Area';

import { DeviceList, DeviceEdit, DevicePanel, DeviceSetting, DeviceDebugNb, DeviceFix } from './pages/Devices';

import { TroubleList, AlarmList } from './pages/Trouble';

import { WorksheetList, WorksheetCreate } from './pages/Worksheet';

// import NavigationSetting from './pages/NavigationSetting';
import NotFound from './pages/NotFound';
import WorkingOn from './pages/WorkingOn';
import KpiComponent from './pages/WorkingOn/Kpi';
import BlankLayout from './layouts/BlankLayout';
import Login from './pages/Login';
import MonitorMap from './pages/MonitorMap';

import OrderManagement from './pages/OrderManagement';
import StaData from './pages/StaData';

import Company, { Signin } from './pages/Company';

import EmployeeList from './pages/EmployeeList';

const autoGeneratedRoutes = [
  {
    path: '/login',
    childRoutes: [],
    component: BlankLayout,
    indexRoute: { component: Login },
  },
  {
    path: '/newdash',
    childRoutes: [],
    component: Newdash,
  },
  {
    path: '/map',
    childRoutes: [],
    component: MonitorMap,
  },
  {
    path: '/setting',
    childRoutes: [
      { path: 'area', childRoutes: [], component: AreaList },
      // { path: 'basic', childRoutes: [], component: BasicSetting },
      { path: 'order', childRoutes: [], component: OrderManagement },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: AreaList },
  },
  {
    path: '/user',
    childRoutes: [
      { path: 'list', childRoutes: [], component: UserList },
      { path: 'pwd', childRoutes: [], component: EditPassword },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: UserList },
  },
  {
    path: '/trouble',
    childRoutes: [
      { path: 'list', childRoutes: [], component: TroubleList },
      { path: 'alarm', childRoutes: [], component: AlarmList },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: TroubleList },
  },
  {
    path: '/devices',
    childRoutes: [
      { path: 'list', childRoutes: [], component: DeviceList },
      { path: 'update', childRoutes: [], component: DeviceEdit },
      { path: 'panel/:sn', childRoutes: [], component: DevicePanel },
      { path: 'fix/:sn', childRoutes: [], component: DeviceFix },
      { path: 'debugnb', childRoutes: [], component: DeviceDebugNb },
      { path: 'setting', childRoutes: [], component: DeviceSetting },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: DeviceList },
  },
  {
    path: '/profile',
    childRoutes: [ ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: UserProfile },
  },
  {
    path: '/worksheet',
    childRoutes: [
      { path: 'list', childRoutes: [], component: WorksheetList },
      { path: 'create', childRoutes: [], component: WorksheetCreate },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: WorksheetList },
  },
  {
    path: '/workingon',
    childRoutes: [
      { path: 'ops', childRoutes: [], component: WorkingOn },
      { path: 'kpi', childRoutes: [], component: KpiComponent },
      { path: 'stadatas', childRoutes: [], component: StaData },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: WorkingOn },
  },
  {
    path:'/operation',
    childRoutes: [
      { path: 'company', childRoutes: [], component: Company },
      { path: 'signin', childRoutes: [], component: Signin },
      { path: 'employee', childRoutes: [], component: EmployeeList },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Company },
  },
  {
    path: '/',
    childRoutes: [{ path: '*', childRoutes: [], component: NotFound }],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Dashboard },
  },
];

// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
